# Generated by Django 6.0 on 2026-01-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=50)),
                ('firstNames', models.CharField(max_length=50)),
                ('grade', models.IntegerField(default=8)),
                ('group', models.CharField(max_length=1)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
